// Shared engine that marks KAHF AI "reads" (generated by scripts/build-top-reads.js)
// to the LIVE options market. Used by /api/top-reads (homepage) and /api/wins
// (full track record) so both pages stay perfectly consistent.

import fs from 'fs';
import path from 'path';
import { getOptionsSnapshot } from './polygon-data-service.js';

const API_BASE = 'https://api.massive.com';

export function loadReadsFile(filename) {
  try {
    const p = path.join(process.cwd(), filename);
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch {
    return { reads: [] };
  }
}

async function getStockCloseOnOrAfter(ticker, date) {
  const end = new Date(`${date}T00:00:00Z`);
  end.setUTCDate(end.getUTCDate() + 7);
  const url = `${API_BASE}/v2/aggs/ticker/${ticker}/range/1/day/${date}/${end
    .toISOString()
    .slice(0, 10)}?adjusted=true&sort=asc&apiKey=${process.env.POLYGON_API_KEY}`;
  try {
    const r = await fetch(url);
    if (!r.ok) return null;
    const data = await r.json();
    return data.results?.[0]?.c ?? null;
  } catch {
    return null;
  }
}

export function structureLabel(s) {
  return s === 'call' ? 'Long Call' : s === 'put' ? 'Long Put' : 'ATM Straddle';
}

// Mark a single read to market. Open -> live option price; settled -> intrinsic
// at expiration. Returns null-safe P/L fields.
export async function markRead(read) {
  const today = new Date().toISOString().slice(0, 10);
  const isOpen = read.expiration >= today;
  const base = {
    date: read.date,
    ticker: read.ticker,
    structure: read.structure,
    structureLabel: structureLabel(read.structure),
    strike: read.strike,
    expiration: read.expiration,
    dte: read.dte,
    volumeRatio: read.volume_ratio,
    darkPoolValue: read.dark_pool_value ?? null,
    asofHitRate: read.asof_hit_rate,
    entryPremium: read.entry_premium
  };

  if (isOpen) {
    const snap = await getOptionsSnapshot(read.ticker, read.contracts);
    const current = read.contracts.reduce((sum, c) => sum + (snap[c]?.price || 0), 0);
    if (current <= 0) {
      return { ...base, status: 'open', currentPremium: null, returnPct: null, priceUnavailable: true };
    }
    const returnPct = ((current - read.entry_premium) / read.entry_premium) * 100;
    return { ...base, status: 'open', currentPremium: Number(current.toFixed(2)), returnPct: Number(returnPct.toFixed(1)) };
  }

  const expClose = await getStockCloseOnOrAfter(read.ticker, read.expiration);
  if (!expClose) {
    return { ...base, status: 'settled', currentPremium: null, returnPct: null, priceUnavailable: true };
  }
  let intrinsic;
  if (read.structure === 'call') intrinsic = Math.max(expClose - read.strike, 0);
  else if (read.structure === 'put') intrinsic = Math.max(read.strike - expClose, 0);
  else intrinsic = Math.abs(expClose - read.strike);
  const returnPct = ((intrinsic - read.entry_premium) / read.entry_premium) * 100;
  return {
    ...base,
    status: 'settled',
    settleClose: Number(expClose.toFixed(2)),
    currentPremium: Number(intrinsic.toFixed(2)),
    returnPct: Number(returnPct.toFixed(1))
  };
}

// Mark a list of reads and compute summary stats.
export async function markReads(reads) {
  const marked = (await Promise.all(reads.map((r) => markRead(r).catch(() => null))))
    .filter(Boolean)
    .sort((a, b) => (a.date < b.date ? 1 : -1));

  const scored = marked.filter((r) => r.returnPct !== null);
  const winners = scored.filter((r) => r.returnPct > 0);
  const losers = scored.filter((r) => r.returnPct < 0);
  const summary = {
    total: marked.length,
    open: marked.filter((r) => r.status === 'open').length,
    settled: marked.filter((r) => r.status === 'settled').length,
    winners: winners.length,
    losers: losers.length,
    hitRate: scored.length ? Math.round((winners.length / scored.length) * 100) : 0,
    avgReturn: scored.length ? Number((scored.reduce((s, r) => s + r.returnPct, 0) / scored.length).toFixed(1)) : 0,
    avgWinner: winners.length ? Number((winners.reduce((s, r) => s + r.returnPct, 0) / winners.length).toFixed(1)) : 0,
    avgLoser: losers.length ? Number((losers.reduce((s, r) => s + r.returnPct, 0) / losers.length).toFixed(1)) : 0
  };

  return { marked, summary };
}

export const READS_DISCLAIMER =
  'Reads are generated by KAHF AI\u2019s scoring model on dark pool signals, then marked to the live options market. Open positions are marked to market; settled positions show realized intrinsic value at expiration (held to expiry \u2014 no active trade management). Hypothetical / backtested \u2014 not live-traded, not advice. Past performance is not indicative of future results.';
