// Shared engine that marks KAHF AI "reads" (generated by scripts/build-top-reads.js)
// to the LIVE options market. Used by /api/top-reads (homepage) and /api/wins
// (full track record) so both pages stay perfectly consistent.

import { getOptionsSnapshot } from './polygon-data-service.js';

const API_BASE = 'https://api.massive.com';

async function getStockCloseOnOrAfter(ticker, date) {
  const end = new Date(`${date}T00:00:00Z`);
  end.setUTCDate(end.getUTCDate() + 7);
  const url = `${API_BASE}/v2/aggs/ticker/${ticker}/range/1/day/${date}/${end
    .toISOString()
    .slice(0, 10)}?adjusted=true&sort=asc&apiKey=${process.env.POLYGON_API_KEY}`;
  // Retry on 429 — marking a full track record fires many requests at once and
  // a silently-dropped close makes the read vanish from the stats/chart.
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const r = await fetch(url);
      if (r.status === 429) {
        await new Promise((s) => setTimeout(s, 1000 * (attempt + 1)));
        continue;
      }
      if (!r.ok) return null;
      const data = await r.json();
      return data.results?.[0]?.c ?? null;
    } catch {
      return null;
    }
  }
  return null;
}

export function structureLabel(s) {
  return s === 'call' ? 'Long Call' : s === 'put' ? 'Long Put' : 'ATM Straddle';
}

// Straddle-only management rule (backtested best mix on YTD 2026): exit at
// +40% take-profit or −30% stop-loss on the combined daily close. Calls and
// puts run to expiry untouched — their winners are the fat right tail, while
// straddles bleed double theta, so only they get managed.
export const STRADDLE_TAKE_PROFIT = 0.4;
export const STRADDLE_STOP_LOSS = 0.3;

async function getOptionDailyCloses(contractTicker, from, to) {
  const url = `${API_BASE}/v2/aggs/ticker/${encodeURIComponent(contractTicker)}/range/1/day/${from}/${to}?adjusted=true&sort=asc&limit=500&apiKey=${process.env.POLYGON_API_KEY}`;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const r = await fetch(url);
      if (r.status === 429) {
        await new Promise((s) => setTimeout(s, 1000 * (attempt + 1)));
        continue;
      }
      if (!r.ok) return [];
      const data = await r.json();
      return (data.results || []).map((b) => ({
        date: new Date(b.t).toISOString().slice(0, 10),
        close: b.c
      }));
    } catch {
      return [];
    }
  }
  return [];
}

// First daily close after entry where the combined straddle value crosses the
// take-profit or stop-loss. Null when the rule never triggered.
async function straddleManagedExit(read, today) {
  if (!Array.isArray(read.contracts) || read.contracts.length !== 2) return null;
  const end = read.expiration < today ? read.expiration : today;
  const [aBars, bBars] = await Promise.all(
    read.contracts.map((c) => getOptionDailyCloses(c, read.date, end))
  );
  const bByDate = new Map(bBars.map((b) => [b.date, b.close]));
  for (const bar of aBars) {
    if (bar.date <= read.date) continue;
    const other = bByDate.get(bar.date);
    if (!other || bar.close <= 0 || other <= 0) continue;
    const value = bar.close + other;
    const ret = (value - read.entry_premium) / read.entry_premium;
    if (ret >= STRADDLE_TAKE_PROFIT) return { exitDate: bar.date, value, reason: 'take-profit' };
    if (ret <= -STRADDLE_STOP_LOSS) return { exitDate: bar.date, value, reason: 'stop-loss' };
  }
  return null;
}

// Mark a single read to market. Open -> live option price; settled -> intrinsic
// at expiration. Returns null-safe P/L fields.
export async function markRead(read) {
  const today = new Date().toISOString().slice(0, 10);
  const isOpen = read.expiration >= today;
  const base = {
    date: read.date,
    ticker: read.ticker,
    foundAt: read.found_at ?? null,
    structure: read.structure,
    structureLabel: structureLabel(read.structure),
    strike: read.strike,
    expiration: read.expiration,
    dte: read.dte,
    volumeRatio: read.volume_ratio,
    darkPoolValue: read.dark_pool_value ?? null,
    asofHitRate: read.asof_hit_rate,
    entryPremium: read.entry_premium
  };

  // Straddles are managed: if the +40%/−30% rule fired on any daily close
  // since entry, the position is closed at that price regardless of expiry.
  if (read.structure === 'straddle') {
    const managed = await straddleManagedExit(read, today);
    if (managed) {
      const returnPct = ((managed.value - read.entry_premium) / read.entry_premium) * 100;
      return {
        ...base,
        status: 'closed',
        exitDate: managed.exitDate,
        exitReason: managed.reason,
        currentPremium: Number(managed.value.toFixed(2)),
        returnPct: Number(returnPct.toFixed(1))
      };
    }
  }

  if (isOpen) {
    const snap = await getOptionsSnapshot(read.ticker, read.contracts);
    const current = read.contracts.reduce((sum, c) => sum + (snap[c]?.price || 0), 0);
    if (current <= 0) {
      return { ...base, status: 'open', currentPremium: null, returnPct: null, priceUnavailable: true };
    }
    const returnPct = ((current - read.entry_premium) / read.entry_premium) * 100;
    return { ...base, status: 'open', currentPremium: Number(current.toFixed(2)), returnPct: Number(returnPct.toFixed(1)) };
  }

  const expClose = await getStockCloseOnOrAfter(read.ticker, read.expiration);
  if (!expClose) {
    return { ...base, status: 'settled', currentPremium: null, returnPct: null, priceUnavailable: true };
  }
  let intrinsic;
  if (read.structure === 'call') intrinsic = Math.max(expClose - read.strike, 0);
  else if (read.structure === 'put') intrinsic = Math.max(read.strike - expClose, 0);
  else intrinsic = Math.abs(expClose - read.strike);
  const returnPct = ((intrinsic - read.entry_premium) / read.entry_premium) * 100;
  return {
    ...base,
    status: 'settled',
    settleClose: Number(expClose.toFixed(2)),
    currentPremium: Number(intrinsic.toFixed(2)),
    returnPct: Number(returnPct.toFixed(1))
  };
}

// Mark a list of reads and compute summary stats. Marked in small batches —
// firing all ~70 reads at once tripped Polygon's rate limit and randomly
// dropped prices, so the published stats changed run to run.
const MARK_BATCH_SIZE = 8;
export async function markReads(reads) {
  const results = [];
  for (let i = 0; i < reads.length; i += MARK_BATCH_SIZE) {
    const batch = reads.slice(i, i + MARK_BATCH_SIZE);
    results.push(...(await Promise.all(batch.map((r) => markRead(r).catch(() => null)))));
  }
  const marked = results
    .filter(Boolean)
    .sort((a, b) => (a.date < b.date ? 1 : -1));

  const scored = marked.filter((r) => r.returnPct !== null);
  const winners = scored.filter((r) => r.returnPct > 0);
  const losers = scored.filter((r) => r.returnPct < 0);
  const summary = {
    total: marked.length,
    open: marked.filter((r) => r.status === 'open').length,
    settled: marked.filter((r) => r.status === 'settled').length,
    closed: marked.filter((r) => r.status === 'closed').length,
    winners: winners.length,
    losers: losers.length,
    hitRate: scored.length ? Math.round((winners.length / scored.length) * 100) : 0,
    avgReturn: scored.length ? Number((scored.reduce((s, r) => s + r.returnPct, 0) / scored.length).toFixed(1)) : 0,
    avgWinner: winners.length ? Number((winners.reduce((s, r) => s + r.returnPct, 0) / winners.length).toFixed(1)) : 0,
    avgLoser: losers.length ? Number((losers.reduce((s, r) => s + r.returnPct, 0) / losers.length).toFixed(1)) : 0
  };

  return { marked, summary };
}

export const READS_DISCLAIMER =
  'Reads are generated by KAHF AI\u2019s scoring model on dark pool signals, then marked to the live options market. Open positions are marked to market; settled calls and puts show realized intrinsic value at expiration (held to expiry). ATM straddles follow a mechanical exit rule: closed at the first daily close beyond +40% (take-profit) or \u221230% (stop-loss). Hypothetical / backtested \u2014 not live-traded, not advice. Past performance is not indicative of future results.';
